repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [ --branch, master, --branch, develop ]
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
      - id: seed-isort-config
  - repo: "https://github.com/pre-commit/mirrors-isort"
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: "https://github.com/ambv/black"
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: "(configs|protos|tests)"
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.2.3
    hooks:
      - id: flake8
        exclude: "(configs|protos|tests)"
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
